# Generated by Django 4.0 on 2022-01-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_testimonal_testimonial_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
