# Generated by Django 4.0 on 2022-04-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_content',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
