# Generated by Django 4.0 on 2022-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_content_video_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='banner_text',
            field=models.CharField(default='Default Text', max_length=254),
            preserve_default=False,
        ),
    ]
